substitutions:
  name: twk-blastgate-brainbox
  friendly_name: TWK Blast Gate 

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

esp8266:
  board: nodemcuv2

output:
- platform: gpio
  pin: GPIO0
  id: direction_pin
- platform: esp8266_pwm
  pin: GPIO5
  id: speed_pin

button:
  - platform: template
    name: "forward"
    on_press:
      #turn on = fowards
      - output.turn_on: direction_pin
      - output.set_level:
          id: speed_pin
          level: 100%
      - wait_until:
          condition:
            # check if the gate is closed, if so, turn off
            lambda : |-
              return true; 

      - delay: 1s
      - output.turn_off: speed_pin
      
  - platform: template
    name: "backwards"
    on_press:
      #turn off = backards
      - output.turn_off: direction_pin
      - output.set_level:
          id: speed_pin
          level: 100%
      - delay: 1s
      - output.turn_off: speed_pin


# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp8266.yaml@main
  import_full_config: true

# To have a "next url" for improv serial
web_server:
